export const LOAD_ALL_NEWS_REQUEST = "LOAD_ALL_NEWS_REQUEST";
export const LOAD_ALL_NEWS_SUCCESS = "LOAD_ALL_NEWS_SUCCESS";

export const LOAD_NEWS_REQUEST = "LOAD_NEWS_REQUEST";
export const LOAD_NEWS_SUCCESS = "LOAD_NEWS_SUCCESS";
export const LOAD_NEWS_FAILURE = "LOAD_NEWS_FAILURE";
export const SET_ACTIVE_NEWS = "SET_ACTIVE_NEWS";

export const LOAD_TAGS_REQUEST = "LOAD_TAGS_REQUEST";
export const LOAD_TAGS_SUCCESS = "LOAD_TAGS_SUCCESS";
export const LOAD_TAGS_FAILURE = "LOAD_TAGS_FAILURE";
export const SELECT_TAG = "SELECT_TAG";